spring.application.name=Loan Management

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/loan_management
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

security.jwt.secret-key=MHcCAQEEILWaQMUB0l9pnfU99kJGMs60nbaWbAioNmfflWl75lEhoAoGCCqGSM49AwEHoUQDQgAEx6oO1Xm8lSi8uiGFGpXWKR9FO/YYp717864IciX1rpIydDLD1ieMnfvYbvZcL+BoZF1Ag99j9Hsm625mTwc76g==
security.jwt.expiration-time=3600000