database.className=org.postgresql.Driver
database.url=jdbc:postgresql://localhost:5432/loan_management
database.username=postgres
database.password=1
entity.package=uz.learn.it.entity
dialect.name=hibernate.dialect
dialect.value=org.hibernate.dialect.PostgreSQLDialect
sql.trace.name=hibernate.show_sql
sql.trace.value=true
database.creation.name=hibernate.hbm2ddl.auto
database.creation.value=create
